//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPED_Gui_WinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Append {
            get {
                return ((bool)(this["General_Append"]));
            }
            set {
                this["General_Append"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Continue {
            get {
                return ((bool)(this["General_Continue"]));
            }
            set {
                this["General_Continue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Download_Internet_Data {
            get {
                return ((bool)(this["General_Download_Internet_Data"]));
            }
            set {
                this["General_Download_Internet_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableAudioTranslation {
            get {
                return ((bool)(this["IPEDConfigEnableAudioTranslation"]));
            }
            set {
                this["IPEDConfigEnableAudioTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableImageClassification {
            get {
                return ((bool)(this["IPEDConfigEnableImageClassification"]));
            }
            set {
                this["IPEDConfigEnableImageClassification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string General_Output_Directory {
            get {
                return ((string)(this["General_Output_Directory"]));
            }
            set {
                this["General_Output_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Portable {
            get {
                return ((bool)(this["General_Portable"]));
            }
            set {
                this["General_Portable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioTranslationProcessVideo {
            get {
                return ((bool)(this["AudioTranslationProcessVideo"]));
            }
            set {
                this["AudioTranslationProcessVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsIpedExePath {
            get {
                return ((string)(this["SettingsIpedExePath"]));
            }
            set {
                this["SettingsIpedExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de-DE")]
        public string LocalConfigLocale {
            get {
                return ((string)(this["LocalConfigLocale"]));
            }
            set {
                this["LocalConfigLocale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalConfigIndexTemp {
            get {
                return ((string)(this["LocalConfigIndexTemp"]));
            }
            set {
                this["LocalConfigIndexTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalConfigIndexTempOnSSD {
            get {
                return ((bool)(this["LocalConfigIndexTempOnSSD"]));
            }
            set {
                this["LocalConfigIndexTempOnSSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalConfigOutputOnSSD {
            get {
                return ((bool)(this["LocalConfigOutputOnSSD"]));
            }
            set {
                this["LocalConfigOutputOnSSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string LocalConfigNumThreads {
            get {
                return ((string)(this["LocalConfigNumThreads"]));
            }
            set {
                this["LocalConfigNumThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalConfigHashesDB {
            get {
                return ((string)(this["LocalConfigHashesDB"]));
            }
            set {
                this["LocalConfigHashesDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalConfigPluginFolder {
            get {
                return ((string)(this["LocalConfigPluginFolder"]));
            }
            set {
                this["LocalConfigPluginFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemConfigAddUnallocated {
            get {
                return ((bool)(this["FileSystemConfigAddUnallocated"]));
            }
            set {
                this["FileSystemConfigAddUnallocated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSystemConfigRobustImageReading {
            get {
                return ((bool)(this["FileSystemConfigRobustImageReading"]));
            }
            set {
                this["FileSystemConfigRobustImageReading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("auto")]
        public string FileSystemConfigNumImageReaders {
            get {
                return ((string)(this["FileSystemConfigNumImageReaders"]));
            }
            set {
                this["FileSystemConfigNumImageReaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSystemConfigAddFileSlacks {
            get {
                return ((bool)(this["FileSystemConfigAddFileSlacks"]));
            }
            set {
                this["FileSystemConfigAddFileSlacks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string FileSystemConfigMinOrphanSizeToIgnore {
            get {
                return ((string)(this["FileSystemConfigMinOrphanSizeToIgnore"]));
            }
            set {
                this["FileSystemConfigMinOrphanSizeToIgnore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1073741824")]
        public string FileSystemConfigUnallocatedFragSize {
            get {
                return ((string)(this["FileSystemConfigUnallocatedFragSize"]));
            }
            set {
                this["FileSystemConfigUnallocatedFragSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemConfigIgnoreHardLinks {
            get {
                return ((bool)(this["FileSystemConfigIgnoreHardLinks"]));
            }
            set {
                this["FileSystemConfigIgnoreHardLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileSystemConfigSkipFolderRegex {
            get {
                return ((string)(this["FileSystemConfigSkipFolderRegex"]));
            }
            set {
                this["FileSystemConfigSkipFolderRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableHash {
            get {
                return ((bool)(this["IPEDConfigEnableHash"]));
            }
            set {
                this["IPEDConfigEnableHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnablePhotoDNA {
            get {
                return ((bool)(this["IPEDConfigEnablePhotoDNA"]));
            }
            set {
                this["IPEDConfigEnablePhotoDNA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableHashDBLookup {
            get {
                return ((bool)(this["IPEDConfigEnableHashDBLookup"]));
            }
            set {
                this["IPEDConfigEnableHashDBLookup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnablePhotoDNALookup {
            get {
                return ((bool)(this["IPEDConfigEnablePhotoDNALookup"]));
            }
            set {
                this["IPEDConfigEnablePhotoDNALookup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableLedDie {
            get {
                return ((bool)(this["IPEDConfigEnableLedDie"]));
            }
            set {
                this["IPEDConfigEnableLedDie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEenableYahooNSFWDetection {
            get {
                return ((bool)(this["IPEDConfigEenableYahooNSFWDetection"]));
            }
            set {
                this["IPEDConfigEenableYahooNSFWDetection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableQRCode {
            get {
                return ((bool)(this["IPEDConfigEnableQRCode"]));
            }
            set {
                this["IPEDConfigEnableQRCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigIgnoreDuplicates {
            get {
                return ((bool)(this["IPEDConfigIgnoreDuplicates"]));
            }
            set {
                this["IPEDConfigIgnoreDuplicates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigExportFileProps {
            get {
                return ((bool)(this["IPEDConfigExportFileProps"]));
            }
            set {
                this["IPEDConfigExportFileProps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigProcessFileSignatures {
            get {
                return ((bool)(this["IPEDConfigProcessFileSignatures"]));
            }
            set {
                this["IPEDConfigProcessFileSignatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableFileParsing {
            get {
                return ((bool)(this["IPEDConfigEnableFileParsing"]));
            }
            set {
                this["IPEDConfigEnableFileParsing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigExpandContainers {
            get {
                return ((bool)(this["IPEDConfigExpandContainers"]));
            }
            set {
                this["IPEDConfigExpandContainers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigProcessEmbeddedDisks {
            get {
                return ((bool)(this["IPEDConfigProcessEmbeddedDisks"]));
            }
            set {
                this["IPEDConfigProcessEmbeddedDisks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableRegexSearch {
            get {
                return ((bool)(this["IPEDConfigEnableRegexSearch"]));
            }
            set {
                this["IPEDConfigEnableRegexSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableAutomaticExportFiles {
            get {
                return ((bool)(this["IPEDConfigEnableAutomaticExportFiles"]));
            }
            set {
                this["IPEDConfigEnableAutomaticExportFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableLanguageDetect {
            get {
                return ((bool)(this["IPEDConfigEnableLanguageDetect"]));
            }
            set {
                this["IPEDConfigEnableLanguageDetect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableNamedEntityRecogniton {
            get {
                return ((bool)(this["IPEDConfigEnableNamedEntityRecogniton"]));
            }
            set {
                this["IPEDConfigEnableNamedEntityRecogniton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableGraphGeneration {
            get {
                return ((bool)(this["IPEDConfigEnableGraphGeneration"]));
            }
            set {
                this["IPEDConfigEnableGraphGeneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEntropyTest {
            get {
                return ((bool)(this["IPEDConfigEntropyTest"]));
            }
            set {
                this["IPEDConfigEntropyTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigIndexFileContents {
            get {
                return ((bool)(this["IPEDConfigIndexFileContents"]));
            }
            set {
                this["IPEDConfigIndexFileContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableIndexToElasticSearch {
            get {
                return ((bool)(this["IPEDConfigEnableIndexToElasticSearch"]));
            }
            set {
                this["IPEDConfigEnableIndexToElasticSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableMinIO {
            get {
                return ((bool)(this["IPEDConfigEnableMinIO"]));
            }
            set {
                this["IPEDConfigEnableMinIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableAudioTranscription {
            get {
                return ((bool)(this["IPEDConfigEnableAudioTranscription"]));
            }
            set {
                this["IPEDConfigEnableAudioTranscription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableCarving {
            get {
                return ((bool)(this["IPEDConfigEnableCarving"]));
            }
            set {
                this["IPEDConfigEnableCarving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableLedCarving {
            get {
                return ((bool)(this["IPEDConfigEnableLedCarving"]));
            }
            set {
                this["IPEDConfigEnableLedCarving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableKnownMetCarving {
            get {
                return ((bool)(this["IPEDConfigEnableKnownMetCarving"]));
            }
            set {
                this["IPEDConfigEnableKnownMetCarving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableImageThumbs {
            get {
                return ((bool)(this["IPEDConfigEnableImageThumbs"]));
            }
            set {
                this["IPEDConfigEnableImageThumbs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableImageSimilarity {
            get {
                return ((bool)(this["IPEDConfigEnableImageSimilarity"]));
            }
            set {
                this["IPEDConfigEnableImageSimilarity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableFaceRecognition {
            get {
                return ((bool)(this["IPEDConfigEnableFaceRecognition"]));
            }
            set {
                this["IPEDConfigEnableFaceRecognition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableVideoThumbs {
            get {
                return ((bool)(this["IPEDConfigEnableVideoThumbs"]));
            }
            set {
                this["IPEDConfigEnableVideoThumbs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableDocThumbs {
            get {
                return ((bool)(this["IPEDConfigEnableDocThumbs"]));
            }
            set {
                this["IPEDConfigEnableDocThumbs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableHTMLReport {
            get {
                return ((bool)(this["IPEDConfigEnableHTMLReport"]));
            }
            set {
                this["IPEDConfigEnableHTMLReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableTextTranslation {
            get {
                return ((bool)(this["IPEDConfigEnableTextTranslation"]));
            }
            set {
                this["IPEDConfigEnableTextTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportDocuments {
            get {
                return ((bool)(this["CategoriesToExportDocuments"]));
            }
            set {
                this["CategoriesToExportDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRTFDocuments {
            get {
                return ((bool)(this["CategoriesToExportRTFDocuments"]));
            }
            set {
                this["CategoriesToExportRTFDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportPDFDocuments {
            get {
                return ((bool)(this["CategoriesToExportPDFDocuments"]));
            }
            set {
                this["CategoriesToExportPDFDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportHTMLDocuments {
            get {
                return ((bool)(this["CategoriesToExportHTMLDocuments"]));
            }
            set {
                this["CategoriesToExportHTMLDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportTextDocuments {
            get {
                return ((bool)(this["CategoriesToExportTextDocuments"]));
            }
            set {
                this["CategoriesToExportTextDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportOtherDocuments {
            get {
                return ((bool)(this["CategoriesToExportOtherDocuments"]));
            }
            set {
                this["CategoriesToExportOtherDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportXMLFiles {
            get {
                return ((bool)(this["CategoriesToExportXMLFiles"]));
            }
            set {
                this["CategoriesToExportXMLFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportGeoreferencedFiles {
            get {
                return ((bool)(this["CategoriesToExportGeoreferencedFiles"]));
            }
            set {
                this["CategoriesToExportGeoreferencedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportSpreadsheets {
            get {
                return ((bool)(this["CategoriesToExportSpreadsheets"]));
            }
            set {
                this["CategoriesToExportSpreadsheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportPresentations {
            get {
                return ((bool)(this["CategoriesToExportPresentations"]));
            }
            set {
                this["CategoriesToExportPresentations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportOLEfiles {
            get {
                return ((bool)(this["CategoriesToExportOLEfiles"]));
            }
            set {
                this["CategoriesToExportOLEfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportLinks {
            get {
                return ((bool)(this["CategoriesToExportLinks"]));
            }
            set {
                this["CategoriesToExportLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportLinkfiles {
            get {
                return ((bool)(this["CategoriesToExportLinkfiles"]));
            }
            set {
                this["CategoriesToExportLinkfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportURLlinks {
            get {
                return ((bool)(this["CategoriesToExportURLlinks"]));
            }
            set {
                this["CategoriesToExportURLlinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportEmailsandMailboxes {
            get {
                return ((bool)(this["CategoriesToExportEmailsandMailboxes"]));
            }
            set {
                this["CategoriesToExportEmailsandMailboxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportMailboxes {
            get {
                return ((bool)(this["CategoriesToExportMailboxes"]));
            }
            set {
                this["CategoriesToExportMailboxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportEmails {
            get {
                return ((bool)(this["CategoriesToExportEmails"]));
            }
            set {
                this["CategoriesToExportEmails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportAppointments {
            get {
                return ((bool)(this["CategoriesToExportAppointments"]));
            }
            set {
                this["CategoriesToExportAppointments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportWin10MailAppAdditionalInfo {
            get {
                return ((bool)(this["CategoriesToExportWin10MailAppAdditionalInfo"]));
            }
            set {
                this["CategoriesToExportWin10MailAppAdditionalInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportMultimedia {
            get {
                return ((bool)(this["CategoriesToExportMultimedia"]));
            }
            set {
                this["CategoriesToExportMultimedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportAudios {
            get {
                return ((bool)(this["CategoriesToExportAudios"]));
            }
            set {
                this["CategoriesToExportAudios"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportVideos {
            get {
                return ((bool)(this["CategoriesToExportVideos"]));
            }
            set {
                this["CategoriesToExportVideos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportVideoThumbnails {
            get {
                return ((bool)(this["CategoriesToExportVideoThumbnails"]));
            }
            set {
                this["CategoriesToExportVideoThumbnails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportImages {
            get {
                return ((bool)(this["CategoriesToExportImages"]));
            }
            set {
                this["CategoriesToExportImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportTemporaryInternetImages {
            get {
                return ((bool)(this["CategoriesToExportTemporaryInternetImages"]));
            }
            set {
                this["CategoriesToExportTemporaryInternetImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportImagesinSystemFolders {
            get {
                return ((bool)(this["CategoriesToExportImagesinSystemFolders"]));
            }
            set {
                this["CategoriesToExportImagesinSystemFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportOtherImages {
            get {
                return ((bool)(this["CategoriesToExportOtherImages"]));
            }
            set {
                this["CategoriesToExportOtherImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportScannedDocuments {
            get {
                return ((bool)(this["CategoriesToExportScannedDocuments"]));
            }
            set {
                this["CategoriesToExportScannedDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportWindowsArtifacts {
            get {
                return ((bool)(this["CategoriesToExportWindowsArtifacts"]));
            }
            set {
                this["CategoriesToExportWindowsArtifacts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportEventFiles {
            get {
                return ((bool)(this["CategoriesToExportEventFiles"]));
            }
            set {
                this["CategoriesToExportEventFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportEventRecords {
            get {
                return ((bool)(this["CategoriesToExportEventRecords"]));
            }
            set {
                this["CategoriesToExportEventRecords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportPrefetchandSuperfetch {
            get {
                return ((bool)(this["CategoriesToExportPrefetchandSuperfetch"]));
            }
            set {
                this["CategoriesToExportPrefetchandSuperfetch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportUserActivities {
            get {
                return ((bool)(this["CategoriesToExportUserActivities"]));
            }
            set {
                this["CategoriesToExportUserActivities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportUserActivitiesEntries {
            get {
                return ((bool)(this["CategoriesToExportUserActivitiesEntries"]));
            }
            set {
                this["CategoriesToExportUserActivitiesEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportWindowsRegistry {
            get {
                return ((bool)(this["CategoriesToExportWindowsRegistry"]));
            }
            set {
                this["CategoriesToExportWindowsRegistry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportMainRegistryFiles {
            get {
                return ((bool)(this["CategoriesToExportMainRegistryFiles"]));
            }
            set {
                this["CategoriesToExportMainRegistryFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportOtherRegistryFiles {
            get {
                return ((bool)(this["CategoriesToExportOtherRegistryFiles"]));
            }
            set {
                this["CategoriesToExportOtherRegistryFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryFullReports {
            get {
                return ((bool)(this["CategoriesToExportRegistryFullReports"]));
            }
            set {
                this["CategoriesToExportRegistryFullReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryCustomReports {
            get {
                return ((bool)(this["CategoriesToExportRegistryCustomReports"]));
            }
            set {
                this["CategoriesToExportRegistryCustomReports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryOSInfo {
            get {
                return ((bool)(this["CategoriesToExportRegistryOSInfo"]));
            }
            set {
                this["CategoriesToExportRegistryOSInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryInstalledApps {
            get {
                return ((bool)(this["CategoriesToExportRegistryInstalledApps"]));
            }
            set {
                this["CategoriesToExportRegistryInstalledApps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryNetworkInfo {
            get {
                return ((bool)(this["CategoriesToExportRegistryNetworkInfo"]));
            }
            set {
                this["CategoriesToExportRegistryNetworkInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryStorageInfo {
            get {
                return ((bool)(this["CategoriesToExportRegistryStorageInfo"]));
            }
            set {
                this["CategoriesToExportRegistryStorageInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryDeviceInfo {
            get {
                return ((bool)(this["CategoriesToExportRegistryDeviceInfo"]));
            }
            set {
                this["CategoriesToExportRegistryDeviceInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryProgramRun {
            get {
                return ((bool)(this["CategoriesToExportRegistryProgramRun"]));
            }
            set {
                this["CategoriesToExportRegistryProgramRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryAutoRun {
            get {
                return ((bool)(this["CategoriesToExportRegistryAutoRun"]));
            }
            set {
                this["CategoriesToExportRegistryAutoRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryLogInfo {
            get {
                return ((bool)(this["CategoriesToExportRegistryLogInfo"]));
            }
            set {
                this["CategoriesToExportRegistryLogInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryMalwareInfo {
            get {
                return ((bool)(this["CategoriesToExportRegistryMalwareInfo"]));
            }
            set {
                this["CategoriesToExportRegistryMalwareInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryWebInfo {
            get {
                return ((bool)(this["CategoriesToExportRegistryWebInfo"]));
            }
            set {
                this["CategoriesToExportRegistryWebInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryUserInfo {
            get {
                return ((bool)(this["CategoriesToExportRegistryUserInfo"]));
            }
            set {
                this["CategoriesToExportRegistryUserInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryUserAccounts {
            get {
                return ((bool)(this["CategoriesToExportRegistryUserAccounts"]));
            }
            set {
                this["CategoriesToExportRegistryUserAccounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryUserActivity {
            get {
                return ((bool)(this["CategoriesToExportRegistryUserActivity"]));
            }
            set {
                this["CategoriesToExportRegistryUserActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryUserFiles {
            get {
                return ((bool)(this["CategoriesToExportRegistryUserFiles"]));
            }
            set {
                this["CategoriesToExportRegistryUserFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryUserNetworkActivity {
            get {
                return ((bool)(this["CategoriesToExportRegistryUserNetworkActivity"]));
            }
            set {
                this["CategoriesToExportRegistryUserNetworkActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryUserConfig {
            get {
                return ((bool)(this["CategoriesToExportRegistryUserConfig"]));
            }
            set {
                this["CategoriesToExportRegistryUserConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryUserVirtualization {
            get {
                return ((bool)(this["CategoriesToExportRegistryUserVirtualization"]));
            }
            set {
                this["CategoriesToExportRegistryUserVirtualization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRegistryUserCommunication {
            get {
                return ((bool)(this["CategoriesToExportRegistryUserCommunication"]));
            }
            set {
                this["CategoriesToExportRegistryUserCommunication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportGoogleDrive {
            get {
                return ((bool)(this["CategoriesToExportGoogleDrive"]));
            }
            set {
                this["CategoriesToExportGoogleDrive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportGDriveSyncedFiles {
            get {
                return ((bool)(this["CategoriesToExportGDriveSyncedFiles"]));
            }
            set {
                this["CategoriesToExportGDriveSyncedFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportGDriveFileEntries {
            get {
                return ((bool)(this["CategoriesToExportGDriveFileEntries"]));
            }
            set {
                this["CategoriesToExportGDriveFileEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportDatabases {
            get {
                return ((bool)(this["CategoriesToExportDatabases"]));
            }
            set {
                this["CategoriesToExportDatabases"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportCompressedArchives {
            get {
                return ((bool)(this["CategoriesToExportCompressedArchives"]));
            }
            set {
                this["CategoriesToExportCompressedArchives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportContacts {
            get {
                return ((bool)(this["CategoriesToExportContacts"]));
            }
            set {
                this["CategoriesToExportContacts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportChats {
            get {
                return ((bool)(this["CategoriesToExportChats"]));
            }
            set {
                this["CategoriesToExportChats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportWhatsApp {
            get {
                return ((bool)(this["CategoriesToExportWhatsApp"]));
            }
            set {
                this["CategoriesToExportWhatsApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportMessenger {
            get {
                return ((bool)(this["CategoriesToExportMessenger"]));
            }
            set {
                this["CategoriesToExportMessenger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportSkype {
            get {
                return ((bool)(this["CategoriesToExportSkype"]));
            }
            set {
                this["CategoriesToExportSkype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportTelegram {
            get {
                return ((bool)(this["CategoriesToExportTelegram"]));
            }
            set {
                this["CategoriesToExportTelegram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportJabber {
            get {
                return ((bool)(this["CategoriesToExportJabber"]));
            }
            set {
                this["CategoriesToExportJabber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportFacebook {
            get {
                return ((bool)(this["CategoriesToExportFacebook"]));
            }
            set {
                this["CategoriesToExportFacebook"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportInstagram {
            get {
                return ((bool)(this["CategoriesToExportInstagram"]));
            }
            set {
                this["CategoriesToExportInstagram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportDiscord {
            get {
                return ((bool)(this["CategoriesToExportDiscord"]));
            }
            set {
                this["CategoriesToExportDiscord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportChatActivities {
            get {
                return ((bool)(this["CategoriesToExportChatActivities"]));
            }
            set {
                this["CategoriesToExportChatActivities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportOthersChats {
            get {
                return ((bool)(this["CategoriesToExportOthersChats"]));
            }
            set {
                this["CategoriesToExportOthersChats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportUSNJournal {
            get {
                return ((bool)(this["CategoriesToExportUSNJournal"]));
            }
            set {
                this["CategoriesToExportUSNJournal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportProgramsandLibraries {
            get {
                return ((bool)(this["CategoriesToExportProgramsandLibraries"]));
            }
            set {
                this["CategoriesToExportProgramsandLibraries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportUnallocated {
            get {
                return ((bool)(this["CategoriesToExportUnallocated"]));
            }
            set {
                this["CategoriesToExportUnallocated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportFileSlacks {
            get {
                return ((bool)(this["CategoriesToExportFileSlacks"]));
            }
            set {
                this["CategoriesToExportFileSlacks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportPlainTexts {
            get {
                return ((bool)(this["CategoriesToExportPlainTexts"]));
            }
            set {
                this["CategoriesToExportPlainTexts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportTemporaryInternetTexts {
            get {
                return ((bool)(this["CategoriesToExportTemporaryInternetTexts"]));
            }
            set {
                this["CategoriesToExportTemporaryInternetTexts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportTextsinSystemFolders {
            get {
                return ((bool)(this["CategoriesToExportTextsinSystemFolders"]));
            }
            set {
                this["CategoriesToExportTextsinSystemFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportOtherTexts {
            get {
                return ((bool)(this["CategoriesToExportOtherTexts"]));
            }
            set {
                this["CategoriesToExportOtherTexts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportOtherfiles {
            get {
                return ((bool)(this["CategoriesToExportOtherfiles"]));
            }
            set {
                this["CategoriesToExportOtherfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportPeertopeer {
            get {
                return ((bool)(this["CategoriesToExportPeertopeer"]));
            }
            set {
                this["CategoriesToExportPeertopeer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportAresGalaxy {
            get {
                return ((bool)(this["CategoriesToExportAresGalaxy"]));
            }
            set {
                this["CategoriesToExportAresGalaxy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportEMule {
            get {
                return ((bool)(this["CategoriesToExportEMule"]));
            }
            set {
                this["CategoriesToExportEMule"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportShareaza {
            get {
                return ((bool)(this["CategoriesToExportShareaza"]));
            }
            set {
                this["CategoriesToExportShareaza"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportTorrent {
            get {
                return ((bool)(this["CategoriesToExportTorrent"]));
            }
            set {
                this["CategoriesToExportTorrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportOtherPeertopeer {
            get {
                return ((bool)(this["CategoriesToExportOtherPeertopeer"]));
            }
            set {
                this["CategoriesToExportOtherPeertopeer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportBrowserArtifacts {
            get {
                return ((bool)(this["CategoriesToExportBrowserArtifacts"]));
            }
            set {
                this["CategoriesToExportBrowserArtifacts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportInternetHistory {
            get {
                return ((bool)(this["CategoriesToExportInternetHistory"]));
            }
            set {
                this["CategoriesToExportInternetHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportInternetHistoryEntries {
            get {
                return ((bool)(this["CategoriesToExportInternetHistoryEntries"]));
            }
            set {
                this["CategoriesToExportInternetHistoryEntries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportWebBookmarks {
            get {
                return ((bool)(this["CategoriesToExportWebBookmarks"]));
            }
            set {
                this["CategoriesToExportWebBookmarks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportMozillaFirefoxSavedSession {
            get {
                return ((bool)(this["CategoriesToExportMozillaFirefoxSavedSession"]));
            }
            set {
                this["CategoriesToExportMozillaFirefoxSavedSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportTorTCFragment {
            get {
                return ((bool)(this["CategoriesToExportTorTCFragment"]));
            }
            set {
                this["CategoriesToExportTorTCFragment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportImageDisks {
            get {
                return ((bool)(this["CategoriesToExportImageDisks"]));
            }
            set {
                this["CategoriesToExportImageDisks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportISOdisks {
            get {
                return ((bool)(this["CategoriesToExportISOdisks"]));
            }
            set {
                this["CategoriesToExportISOdisks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportVirtualdisks {
            get {
                return ((bool)(this["CategoriesToExportVirtualdisks"]));
            }
            set {
                this["CategoriesToExportVirtualdisks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportOtherdisks {
            get {
                return ((bool)(this["CategoriesToExportOtherdisks"]));
            }
            set {
                this["CategoriesToExportOtherdisks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportExtractionSummary {
            get {
                return ((bool)(this["CategoriesToExportExtractionSummary"]));
            }
            set {
                this["CategoriesToExportExtractionSummary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportCalls {
            get {
                return ((bool)(this["CategoriesToExportCalls"]));
            }
            set {
                this["CategoriesToExportCalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportSMSMessages {
            get {
                return ((bool)(this["CategoriesToExportSMSMessages"]));
            }
            set {
                this["CategoriesToExportSMSMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportMMSMessages {
            get {
                return ((bool)(this["CategoriesToExportMMSMessages"]));
            }
            set {
                this["CategoriesToExportMMSMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportInstantMessages {
            get {
                return ((bool)(this["CategoriesToExportInstantMessages"]));
            }
            set {
                this["CategoriesToExportInstantMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportBluetoothDevices {
            get {
                return ((bool)(this["CategoriesToExportBluetoothDevices"]));
            }
            set {
                this["CategoriesToExportBluetoothDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportSIMData {
            get {
                return ((bool)(this["CategoriesToExportSIMData"]));
            }
            set {
                this["CategoriesToExportSIMData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportCalendar {
            get {
                return ((bool)(this["CategoriesToExportCalendar"]));
            }
            set {
                this["CategoriesToExportCalendar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportLogs {
            get {
                return ((bool)(this["CategoriesToExportLogs"]));
            }
            set {
                this["CategoriesToExportLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportUserAccounts {
            get {
                return ((bool)(this["CategoriesToExportUserAccounts"]));
            }
            set {
                this["CategoriesToExportUserAccounts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportSearches {
            get {
                return ((bool)(this["CategoriesToExportSearches"]));
            }
            set {
                this["CategoriesToExportSearches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportNotes {
            get {
                return ((bool)(this["CategoriesToExportNotes"]));
            }
            set {
                this["CategoriesToExportNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportWirelessNetworks {
            get {
                return ((bool)(this["CategoriesToExportWirelessNetworks"]));
            }
            set {
                this["CategoriesToExportWirelessNetworks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportNotifications {
            get {
                return ((bool)(this["CategoriesToExportNotifications"]));
            }
            set {
                this["CategoriesToExportNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportLocations {
            get {
                return ((bool)(this["CategoriesToExportLocations"]));
            }
            set {
                this["CategoriesToExportLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportCookies {
            get {
                return ((bool)(this["CategoriesToExportCookies"]));
            }
            set {
                this["CategoriesToExportCookies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportConfiguration {
            get {
                return ((bool)(this["CategoriesToExportConfiguration"]));
            }
            set {
                this["CategoriesToExportConfiguration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportPasswords {
            get {
                return ((bool)(this["CategoriesToExportPasswords"]));
            }
            set {
                this["CategoriesToExportPasswords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportAutofill {
            get {
                return ((bool)(this["CategoriesToExportAutofill"]));
            }
            set {
                this["CategoriesToExportAutofill"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportCellTowers {
            get {
                return ((bool)(this["CategoriesToExportCellTowers"]));
            }
            set {
                this["CategoriesToExportCellTowers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportPowerEvents {
            get {
                return ((bool)(this["CategoriesToExportPowerEvents"]));
            }
            set {
                this["CategoriesToExportPowerEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportUserDictionaries {
            get {
                return ((bool)(this["CategoriesToExportUserDictionaries"]));
            }
            set {
                this["CategoriesToExportUserDictionaries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportIPConnections {
            get {
                return ((bool)(this["CategoriesToExportIPConnections"]));
            }
            set {
                this["CategoriesToExportIPConnections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRecordings {
            get {
                return ((bool)(this["CategoriesToExportRecordings"]));
            }
            set {
                this["CategoriesToExportRecordings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportMobileCards {
            get {
                return ((bool)(this["CategoriesToExportMobileCards"]));
            }
            set {
                this["CategoriesToExportMobileCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportApplicationsUsage {
            get {
                return ((bool)(this["CategoriesToExportApplicationsUsage"]));
            }
            set {
                this["CategoriesToExportApplicationsUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportDeviceInformation {
            get {
                return ((bool)(this["CategoriesToExportDeviceInformation"]));
            }
            set {
                this["CategoriesToExportDeviceInformation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportActivitiesSensor {
            get {
                return ((bool)(this["CategoriesToExportActivitiesSensor"]));
            }
            set {
                this["CategoriesToExportActivitiesSensor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportCreditCards {
            get {
                return ((bool)(this["CategoriesToExportCreditCards"]));
            }
            set {
                this["CategoriesToExportCreditCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportDeviceConnectivity {
            get {
                return ((bool)(this["CategoriesToExportDeviceConnectivity"]));
            }
            set {
                this["CategoriesToExportDeviceConnectivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportDeviceEvents {
            get {
                return ((bool)(this["CategoriesToExportDeviceEvents"]));
            }
            set {
                this["CategoriesToExportDeviceEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportFileDownloads {
            get {
                return ((bool)(this["CategoriesToExportFileDownloads"]));
            }
            set {
                this["CategoriesToExportFileDownloads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportJourneys {
            get {
                return ((bool)(this["CategoriesToExportJourneys"]));
            }
            set {
                this["CategoriesToExportJourneys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportNetworksUsage {
            get {
                return ((bool)(this["CategoriesToExportNetworksUsage"]));
            }
            set {
                this["CategoriesToExportNetworksUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRecognizedDevices {
            get {
                return ((bool)(this["CategoriesToExportRecognizedDevices"]));
            }
            set {
                this["CategoriesToExportRecognizedDevices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportSocialMediaActivities {
            get {
                return ((bool)(this["CategoriesToExportSocialMediaActivities"]));
            }
            set {
                this["CategoriesToExportSocialMediaActivities"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GeneralSearchTermFilePath {
            get {
                return ((string)(this["GeneralSearchTermFilePath"]));
            }
            set {
                this["GeneralSearchTermFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationTaskBridgeUrl {
            get {
                return ((string)(this["AudioTranslationTaskBridgeUrl"]));
            }
            set {
                this["AudioTranslationTaskBridgeUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationTaskBridgeUrl {
            get {
                return ((string)(this["ImageClassificationTaskBridgeUrl"]));
            }
            set {
                this["ImageClassificationTaskBridgeUrl"] = value;
            }
        }
    }
}
