//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPED_Gui_WinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Append {
            get {
                return ((bool)(this["General_Append"]));
            }
            set {
                this["General_Append"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Continue {
            get {
                return ((bool)(this["General_Continue"]));
            }
            set {
                this["General_Continue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Download_Internet_Data {
            get {
                return ((bool)(this["General_Download_Internet_Data"]));
            }
            set {
                this["General_Download_Internet_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableAudioTranslation {
            get {
                return ((bool)(this["IPEDConfigEnableAudioTranslation"]));
            }
            set {
                this["IPEDConfigEnableAudioTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableImageClassification {
            get {
                return ((bool)(this["IPEDConfigEnableImageClassification"]));
            }
            set {
                this["IPEDConfigEnableImageClassification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string General_Output_Directory {
            get {
                return ((string)(this["General_Output_Directory"]));
            }
            set {
                this["General_Output_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Portable {
            get {
                return ((bool)(this["General_Portable"]));
            }
            set {
                this["General_Portable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationInputDirectory {
            get {
                return ((string)(this["AudioTranslationInputDirectory"]));
            }
            set {
                this["AudioTranslationInputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationOutputDirectory {
            get {
                return ((string)(this["AudioTranslationOutputDirectory"]));
            }
            set {
                this["AudioTranslationOutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioTranslationProcessVideo {
            get {
                return ((bool)(this["AudioTranslationProcessVideo"]));
            }
            set {
                this["AudioTranslationProcessVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationInputDirectory {
            get {
                return ((string)(this["ImageClassificationInputDirectory"]));
            }
            set {
                this["ImageClassificationInputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationOutputDirectory {
            get {
                return ((string)(this["ImageClassificationOutputDirectory"]));
            }
            set {
                this["ImageClassificationOutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsIpedExePath {
            get {
                return ((string)(this["SettingsIpedExePath"]));
            }
            set {
                this["SettingsIpedExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de-DE")]
        public string SettingsLocale {
            get {
                return ((string)(this["SettingsLocale"]));
            }
            set {
                this["SettingsLocale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsIndexTemp {
            get {
                return ((string)(this["SettingsIndexTemp"]));
            }
            set {
                this["SettingsIndexTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsIndexTempOnSSD {
            get {
                return ((bool)(this["SettingsIndexTempOnSSD"]));
            }
            set {
                this["SettingsIndexTempOnSSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsOutputOnSSD {
            get {
                return ((bool)(this["SettingsOutputOnSSD"]));
            }
            set {
                this["SettingsOutputOnSSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string SettingsNumThreads {
            get {
                return ((string)(this["SettingsNumThreads"]));
            }
            set {
                this["SettingsNumThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsHashesDB {
            get {
                return ((string)(this["SettingsHashesDB"]));
            }
            set {
                this["SettingsHashesDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsPluginFolder {
            get {
                return ((string)(this["SettingsPluginFolder"]));
            }
            set {
                this["SettingsPluginFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationServiceProgram {
            get {
                return ((string)(this["AudioTranslationServiceProgram"]));
            }
            set {
                this["AudioTranslationServiceProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationProcessingDirectory {
            get {
                return ((string)(this["AudioTranslationProcessingDirectory"]));
            }
            set {
                this["AudioTranslationProcessingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationFasterWhisperDirectory {
            get {
                return ((string)(this["AudioTranslationFasterWhisperDirectory"]));
            }
            set {
                this["AudioTranslationFasterWhisperDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationArgosTranslateDirectory {
            get {
                return ((string)(this["AudioTranslationArgosTranslateDirectory"]));
            }
            set {
                this["AudioTranslationArgosTranslateDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("large-v2")]
        public string AudioTranslationModelSize {
            get {
                return ((string)(this["AudioTranslationModelSize"]));
            }
            set {
                this["AudioTranslationModelSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioTranslationUseGPU {
            get {
                return ((bool)(this["AudioTranslationUseGPU"]));
            }
            set {
                this["AudioTranslationUseGPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationServiceProgram {
            get {
                return ((string)(this["ImageClassificationServiceProgram"]));
            }
            set {
                this["ImageClassificationServiceProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationProcessingDirectory {
            get {
                return ((string)(this["ImageClassificationProcessingDirectory"]));
            }
            set {
                this["ImageClassificationProcessingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationMobileNetDirectory {
            get {
                return ((string)(this["ImageClassificationMobileNetDirectory"]));
            }
            set {
                this["ImageClassificationMobileNetDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de")]
        public string ImageClassificationLanguage {
            get {
                return ((string)(this["ImageClassificationLanguage"]));
            }
            set {
                this["ImageClassificationLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsEnableCarving {
            get {
                return ((bool)(this["SettingsEnableCarving"]));
            }
            set {
                this["SettingsEnableCarving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemConfigAddUnallocated {
            get {
                return ((bool)(this["FileSystemConfigAddUnallocated"]));
            }
            set {
                this["FileSystemConfigAddUnallocated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsEnableFaceRecognition {
            get {
                return ((bool)(this["SettingsEnableFaceRecognition"]));
            }
            set {
                this["SettingsEnableFaceRecognition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsEnableGraphGeneration {
            get {
                return ((bool)(this["SettingsEnableGraphGeneration"]));
            }
            set {
                this["SettingsEnableGraphGeneration"] = value;
            }
        }
    }
}
