//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPED_Gui_WinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Append {
            get {
                return ((bool)(this["General_Append"]));
            }
            set {
                this["General_Append"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Continue {
            get {
                return ((bool)(this["General_Continue"]));
            }
            set {
                this["General_Continue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Download_Internet_Data {
            get {
                return ((bool)(this["General_Download_Internet_Data"]));
            }
            set {
                this["General_Download_Internet_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableAudioTranslation {
            get {
                return ((bool)(this["IPEDConfigEnableAudioTranslation"]));
            }
            set {
                this["IPEDConfigEnableAudioTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableImageClassification {
            get {
                return ((bool)(this["IPEDConfigEnableImageClassification"]));
            }
            set {
                this["IPEDConfigEnableImageClassification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string General_Output_Directory {
            get {
                return ((string)(this["General_Output_Directory"]));
            }
            set {
                this["General_Output_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Portable {
            get {
                return ((bool)(this["General_Portable"]));
            }
            set {
                this["General_Portable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationInputDirectory {
            get {
                return ((string)(this["AudioTranslationInputDirectory"]));
            }
            set {
                this["AudioTranslationInputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationOutputDirectory {
            get {
                return ((string)(this["AudioTranslationOutputDirectory"]));
            }
            set {
                this["AudioTranslationOutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AudioTranslationProcessVideo {
            get {
                return ((bool)(this["AudioTranslationProcessVideo"]));
            }
            set {
                this["AudioTranslationProcessVideo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationInputDirectory {
            get {
                return ((string)(this["ImageClassificationInputDirectory"]));
            }
            set {
                this["ImageClassificationInputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationOutputDirectory {
            get {
                return ((string)(this["ImageClassificationOutputDirectory"]));
            }
            set {
                this["ImageClassificationOutputDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsIpedExePath {
            get {
                return ((string)(this["SettingsIpedExePath"]));
            }
            set {
                this["SettingsIpedExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de-DE")]
        public string LocalConfigLocale {
            get {
                return ((string)(this["LocalConfigLocale"]));
            }
            set {
                this["LocalConfigLocale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalConfigIndexTemp {
            get {
                return ((string)(this["LocalConfigIndexTemp"]));
            }
            set {
                this["LocalConfigIndexTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalConfigIndexTempOnSSD {
            get {
                return ((bool)(this["LocalConfigIndexTempOnSSD"]));
            }
            set {
                this["LocalConfigIndexTempOnSSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalConfigOutputOnSSD {
            get {
                return ((bool)(this["LocalConfigOutputOnSSD"]));
            }
            set {
                this["LocalConfigOutputOnSSD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string LocalConfigNumThreads {
            get {
                return ((string)(this["LocalConfigNumThreads"]));
            }
            set {
                this["LocalConfigNumThreads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalConfigHashesDB {
            get {
                return ((string)(this["LocalConfigHashesDB"]));
            }
            set {
                this["LocalConfigHashesDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalConfigPluginFolder {
            get {
                return ((string)(this["LocalConfigPluginFolder"]));
            }
            set {
                this["LocalConfigPluginFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationServiceProgram {
            get {
                return ((string)(this["AudioTranslationServiceProgram"]));
            }
            set {
                this["AudioTranslationServiceProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationProcessingDirectory {
            get {
                return ((string)(this["AudioTranslationProcessingDirectory"]));
            }
            set {
                this["AudioTranslationProcessingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationFasterWhisperDirectory {
            get {
                return ((string)(this["AudioTranslationFasterWhisperDirectory"]));
            }
            set {
                this["AudioTranslationFasterWhisperDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioTranslationArgosTranslateDirectory {
            get {
                return ((string)(this["AudioTranslationArgosTranslateDirectory"]));
            }
            set {
                this["AudioTranslationArgosTranslateDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("large-v2")]
        public string AudioTranslationModelSize {
            get {
                return ((string)(this["AudioTranslationModelSize"]));
            }
            set {
                this["AudioTranslationModelSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AudioTranslationUseGPU {
            get {
                return ((bool)(this["AudioTranslationUseGPU"]));
            }
            set {
                this["AudioTranslationUseGPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationServiceProgram {
            get {
                return ((string)(this["ImageClassificationServiceProgram"]));
            }
            set {
                this["ImageClassificationServiceProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationProcessingDirectory {
            get {
                return ((string)(this["ImageClassificationProcessingDirectory"]));
            }
            set {
                this["ImageClassificationProcessingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageClassificationMobileNetDirectory {
            get {
                return ((string)(this["ImageClassificationMobileNetDirectory"]));
            }
            set {
                this["ImageClassificationMobileNetDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("de")]
        public string ImageClassificationLanguage {
            get {
                return ((string)(this["ImageClassificationLanguage"]));
            }
            set {
                this["ImageClassificationLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemConfigAddUnallocated {
            get {
                return ((bool)(this["FileSystemConfigAddUnallocated"]));
            }
            set {
                this["FileSystemConfigAddUnallocated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSystemConfigRobustImageReading {
            get {
                return ((bool)(this["FileSystemConfigRobustImageReading"]));
            }
            set {
                this["FileSystemConfigRobustImageReading"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("auto")]
        public string FileSystemConfigNumImageReaders {
            get {
                return ((string)(this["FileSystemConfigNumImageReaders"]));
            }
            set {
                this["FileSystemConfigNumImageReaders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileSystemConfigAddFileSlacks {
            get {
                return ((bool)(this["FileSystemConfigAddFileSlacks"]));
            }
            set {
                this["FileSystemConfigAddFileSlacks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public string FileSystemConfigMinOrphanSizeToIgnore {
            get {
                return ((string)(this["FileSystemConfigMinOrphanSizeToIgnore"]));
            }
            set {
                this["FileSystemConfigMinOrphanSizeToIgnore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1073741824")]
        public string FileSystemConfigUnallocatedFragSize {
            get {
                return ((string)(this["FileSystemConfigUnallocatedFragSize"]));
            }
            set {
                this["FileSystemConfigUnallocatedFragSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FileSystemConfigIgnoreHardLinks {
            get {
                return ((bool)(this["FileSystemConfigIgnoreHardLinks"]));
            }
            set {
                this["FileSystemConfigIgnoreHardLinks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FileSystemConfigSkipFolderRegex {
            get {
                return ((string)(this["FileSystemConfigSkipFolderRegex"]));
            }
            set {
                this["FileSystemConfigSkipFolderRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableHash {
            get {
                return ((bool)(this["IPEDConfigEnableHash"]));
            }
            set {
                this["IPEDConfigEnableHash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnablePhotoDNA {
            get {
                return ((bool)(this["IPEDConfigEnablePhotoDNA"]));
            }
            set {
                this["IPEDConfigEnablePhotoDNA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableHashDBLookup {
            get {
                return ((bool)(this["IPEDConfigEnableHashDBLookup"]));
            }
            set {
                this["IPEDConfigEnableHashDBLookup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnablePhotoDNALookup {
            get {
                return ((bool)(this["IPEDConfigEnablePhotoDNALookup"]));
            }
            set {
                this["IPEDConfigEnablePhotoDNALookup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableLedDie {
            get {
                return ((bool)(this["IPEDConfigEnableLedDie"]));
            }
            set {
                this["IPEDConfigEnableLedDie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEenableYahooNSFWDetection {
            get {
                return ((bool)(this["IPEDConfigEenableYahooNSFWDetection"]));
            }
            set {
                this["IPEDConfigEenableYahooNSFWDetection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableQRCode {
            get {
                return ((bool)(this["IPEDConfigEnableQRCode"]));
            }
            set {
                this["IPEDConfigEnableQRCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigIgnoreDuplicates {
            get {
                return ((bool)(this["IPEDConfigIgnoreDuplicates"]));
            }
            set {
                this["IPEDConfigIgnoreDuplicates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigExportFileProps {
            get {
                return ((bool)(this["IPEDConfigExportFileProps"]));
            }
            set {
                this["IPEDConfigExportFileProps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigProcessFileSignatures {
            get {
                return ((bool)(this["IPEDConfigProcessFileSignatures"]));
            }
            set {
                this["IPEDConfigProcessFileSignatures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableFileParsing {
            get {
                return ((bool)(this["IPEDConfigEnableFileParsing"]));
            }
            set {
                this["IPEDConfigEnableFileParsing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigExpandContainers {
            get {
                return ((bool)(this["IPEDConfigExpandContainers"]));
            }
            set {
                this["IPEDConfigExpandContainers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigProcessEmbeddedDisks {
            get {
                return ((bool)(this["IPEDConfigProcessEmbeddedDisks"]));
            }
            set {
                this["IPEDConfigProcessEmbeddedDisks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableRegexSearch {
            get {
                return ((bool)(this["IPEDConfigEnableRegexSearch"]));
            }
            set {
                this["IPEDConfigEnableRegexSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableAutomaticExportFiles {
            get {
                return ((bool)(this["IPEDConfigEnableAutomaticExportFiles"]));
            }
            set {
                this["IPEDConfigEnableAutomaticExportFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableLanguageDetect {
            get {
                return ((bool)(this["IPEDConfigEnableLanguageDetect"]));
            }
            set {
                this["IPEDConfigEnableLanguageDetect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableNamedEntityRecogniton {
            get {
                return ((bool)(this["IPEDConfigEnableNamedEntityRecogniton"]));
            }
            set {
                this["IPEDConfigEnableNamedEntityRecogniton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableGraphGeneration {
            get {
                return ((bool)(this["IPEDConfigEnableGraphGeneration"]));
            }
            set {
                this["IPEDConfigEnableGraphGeneration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEntropyTest {
            get {
                return ((bool)(this["IPEDConfigEntropyTest"]));
            }
            set {
                this["IPEDConfigEntropyTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigIndexFileContents {
            get {
                return ((bool)(this["IPEDConfigIndexFileContents"]));
            }
            set {
                this["IPEDConfigIndexFileContents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableIndexToElasticSearch {
            get {
                return ((bool)(this["IPEDConfigEnableIndexToElasticSearch"]));
            }
            set {
                this["IPEDConfigEnableIndexToElasticSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableMinIO {
            get {
                return ((bool)(this["IPEDConfigEnableMinIO"]));
            }
            set {
                this["IPEDConfigEnableMinIO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableAudioTranscription {
            get {
                return ((bool)(this["IPEDConfigEnableAudioTranscription"]));
            }
            set {
                this["IPEDConfigEnableAudioTranscription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableCarving {
            get {
                return ((bool)(this["IPEDConfigEnableCarving"]));
            }
            set {
                this["IPEDConfigEnableCarving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableLedCarving {
            get {
                return ((bool)(this["IPEDConfigEnableLedCarving"]));
            }
            set {
                this["IPEDConfigEnableLedCarving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableKnownMetCarving {
            get {
                return ((bool)(this["IPEDConfigEnableKnownMetCarving"]));
            }
            set {
                this["IPEDConfigEnableKnownMetCarving"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableImageThumbs {
            get {
                return ((bool)(this["IPEDConfigEnableImageThumbs"]));
            }
            set {
                this["IPEDConfigEnableImageThumbs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableImageSimilarity {
            get {
                return ((bool)(this["IPEDConfigEnableImageSimilarity"]));
            }
            set {
                this["IPEDConfigEnableImageSimilarity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableFaceRecognition {
            get {
                return ((bool)(this["IPEDConfigEnableFaceRecognition"]));
            }
            set {
                this["IPEDConfigEnableFaceRecognition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableVideoThumbs {
            get {
                return ((bool)(this["IPEDConfigEnableVideoThumbs"]));
            }
            set {
                this["IPEDConfigEnableVideoThumbs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableDocThumbs {
            get {
                return ((bool)(this["IPEDConfigEnableDocThumbs"]));
            }
            set {
                this["IPEDConfigEnableDocThumbs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IPEDConfigEnableHTMLReport {
            get {
                return ((bool)(this["IPEDConfigEnableHTMLReport"]));
            }
            set {
                this["IPEDConfigEnableHTMLReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfigEnableTextTranslation {
            get {
                return ((bool)(this["IPEDConfigEnableTextTranslation"]));
            }
            set {
                this["IPEDConfigEnableTextTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportDocuments {
            get {
                return ((bool)(this["CategoriesToExportDocuments"]));
            }
            set {
                this["CategoriesToExportDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportRTFDocuments {
            get {
                return ((bool)(this["CategoriesToExportRTFDocuments"]));
            }
            set {
                this["CategoriesToExportRTFDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportPDFDocuments {
            get {
                return ((bool)(this["CategoriesToExportPDFDocuments"]));
            }
            set {
                this["CategoriesToExportPDFDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CategoriesToExportXMLFiles {
            get {
                return ((bool)(this["CategoriesToExportXMLFiles"]));
            }
            set {
                this["CategoriesToExportXMLFiles"] = value;
            }
        }
    }
}
