//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPED_Gui_WinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\")]
        public string General_Iped_Exe_Path {
            get {
                return ((string)(this["General_Iped_Exe_Path"]));
            }
            set {
                this["General_Iped_Exe_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IPEDConfig.txt")]
        public string General_Relative_IPEDConfig_File_Path {
            get {
                return ((string)(this["General_Relative_IPEDConfig_File_Path"]));
            }
            set {
                this["General_Relative_IPEDConfig_File_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("conf/OCRConfig.txt")]
        public string General_Relative_OCRConfig_File_Path {
            get {
                return ((string)(this["General_Relative_OCRConfig_File_Path"]));
            }
            set {
                this["General_Relative_OCRConfig_File_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Append {
            get {
                return ((bool)(this["General_Append"]));
            }
            set {
                this["General_Append"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Continue {
            get {
                return ((bool)(this["General_Continue"]));
            }
            set {
                this["General_Continue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Download_Internet_Data {
            get {
                return ((bool)(this["General_Download_Internet_Data"]));
            }
            set {
                this["General_Download_Internet_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfig_enableAudioTranslation {
            get {
                return ((bool)(this["IPEDConfig_enableAudioTranslation"]));
            }
            set {
                this["IPEDConfig_enableAudioTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IPEDConfig_enableImageClassification {
            get {
                return ((bool)(this["IPEDConfig_enableImageClassification"]));
            }
            set {
                this["IPEDConfig_enableImageClassification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Ocr {
            get {
                return ((bool)(this["General_Ocr"]));
            }
            set {
                this["General_Ocr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\")]
        public string General_Output_Directory {
            get {
                return ((string)(this["General_Output_Directory"]));
            }
            set {
                this["General_Output_Directory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_Portable {
            get {
                return ((bool)(this["General_Portable"]));
            }
            set {
                this["General_Portable"] = value;
            }
        }
    }
}
