name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: IPED_GUI.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the app
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    # Determine app version
    - name: Determine app version of normal GUI
      id: versiongui
      run: echo "::set-output name=version::$([xml]$Data=Get-Content ./IPED_Gui/IPED_Gui.csproj;('' + $Data.Project.PropertyGroup.Version).Trim())"
    - name: Determine app version of simple GUI
      id: versionguisimple
      run: echo "::set-output name=version::$([xml]$Data=Get-Content ./IPED_Gui_Simple/IPED_Gui_Simple.csproj;('' + $Data.Project.PropertyGroup.Version).Trim())"

    - name: Zip GUI Folder
      run: Compress-Archive -Path ./IPED_Gui/bin/Release/net6.0-windows/* -DestinationPath ./IPED-GUI-${{ steps.versiongui.outputs.version }}.zip

    - name: Zip Simple Folder
      run: Compress-Archive -Path ./IPED_Gui_Simple/bin/Release/net6.0-windows/* -DestinationPath ./IPED-GUI-SIMPLE-${{ steps.versionguisimple.outputs.version }}.zip

    - name: Create or update release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./IPED-GUI-${{ steps.version.outputs.version }}.zip,./IPED-GUI-SIMPLE-${{ steps.version.outputs.version }}.zip"
        tag: v${{ steps.versiongui.outputs.version }}
        allowUpdates: true
        name: ${{ steps.versiongui.outputs.version }}
        bodyFile: RELEASENOTES.md
        removeArtifact: true
        replacesArtifacts: true
        token: ${{ github.token }}
        artifactContentType: application/zip
