name: Package JavaFX

on:
  push:
    branches: [ "javafx" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        java-package: 'jdk+fx'
        distribution: 'liberica'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Determine output file name
      id: outputFile
      run: buildfilename=mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout >> "$GITHUB_OUTPUT"

    - name: Determine version
      id: version
      run: version=mvn help:evaluate -Dexpression=project.version -q -DforceStdout >> "$GITHUB_OUTPUT"

    - name: Zip Folder
      run: zip ./${{ steps.outputFile.outputs.buildfilename }}.zip ./target/release/*

    - name: Create or update release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./${{ steps.outputFile.outputs.buildfilename }}.zip"
        tag: v${{ steps.version.outputs.version }}
        allowUpdates: true
        name: ${{ steps.version.outputs.version }}
        bodyFile: RELEASENOTES.md
        removeArtifact: true
        replacesArtifacts: true
        token: ${{ github.token }}
        artifactContentType: application/zip
